# Generated by Django 3.2 on 2024-11-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('sales_volume', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_info',
        ),
    ]
